name: newRelease

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Release Information
        run: |
          echo "A new release has been created with tag name: ${{ github.event.release.tag_name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"