name: newRelease

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram Group
        env:
          VERSION: ${{ github.event.release.tag_name }}
          URL: ${{ github.event.release.html_url }}
        run: bash .github/workflows/newRelease.sh