name: newRelease

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram Group
        env:
          VERSION:
          URL:
        run: bash .github/workflows/newRelease.sh